fail_fast: false
minimum_pre_commit_version: "3.0.0"
default_stages:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: claude-permissions
        name: "Claude permissions policy"
        entry: python /home/user01/infrastructure/scripts/claude-permissions/check_claude_template.py
        language: system
        pass_filenames: false
        stages:
          - pre-commit
