# ARES Project Configuration
# Documentation Agent System Configuration File

project:
  name: "ARES"
  full_name: "Agent Reliability Enforcement System"
  version: "0.1.0"
  description: "Intelligent agent reliability monitoring and enforcement framework"

  # Project metadata
  start_date: "2025-07-15"
  target_completion: "2025-09-15"
  project_manager: "@tech-lead-orchestrator"
  technical_lead: "@project-documentation-agent"

  # Repository information
  repository:
    url: "https://github.com/Neikan-BSN/ARES.git"
    branch: "main"
    backup_branches: ["develop", "feature/documentation-agent"]

# Documentation System Configuration
documentation:
  auto_update:
    enabled: true
    interval_minutes: 15
    background_service: true

  master_documents:
    - name: "PROJECT_ROADMAP.md"
      update_frequency: "weekly"
      data_sources: ["milestones", "git_stats", "code_metrics"]

    - name: "DEVELOPMENT_STATUS.md"
      update_frequency: "daily"
      data_sources: ["git_stats", "code_metrics", "agent_activities"]

    - name: "AGENT_COORDINATION_LOG.md"
      update_frequency: "15_minutes"
      data_sources: ["agent_activities", "workflows", "task_handoffs"]

    - name: "TECHNICAL_DEBT_REGISTRY.md"
      update_frequency: "daily"
      data_sources: ["technical_debt", "resolution_timeline"]

    - name: "INTEGRATION_CHECKPOINTS.md"
      update_frequency: "hourly"
      data_sources: ["integration_checkpoints", "system_health"]

  tracking_documents:
    - name: "MILESTONE_TRACKER.md"
      update_frequency: "15_minutes"
      location: "tracker/"

    - name: "AGENT_PERFORMANCE_TRACKER.md"
      update_frequency: "15_minutes"
      location: "tracker/"

    - name: "DAILY_STATUS_REPORT.md"
      update_frequency: "daily"
      location: "reports/"

# Agent System Configuration
agents:
  orchestration:
    - name: "@tech-lead-orchestrator"
      role: "Primary coordinator"
      capabilities: ["task_breakdown", "agent_routing", "dependency_management"]
      priority: "critical"

    - name: "@project-analyst"
      role: "Deep analysis"
      capabilities: ["architectural_analysis", "dependency_mapping"]
      priority: "high"

    - name: "@team-configurator"
      role: "Team optimization"
      capabilities: ["agent_routing", "performance_optimization"]
      priority: "medium"

  core_development:
    - name: "@code-archaeologist"
      role: "Codebase exploration"
      capabilities: ["pattern_discovery", "architectural_documentation"]
      priority: "high"

    - name: "@code-reviewer"
      role: "Quality assurance"
      capabilities: ["security_validation", "quality_metrics"]
      priority: "high"

    - name: "@documentation-specialist"
      role: "Technical documentation"
      capabilities: ["documentation_creation", "knowledge_synthesis"]
      priority: "medium"

    - name: "@performance-optimizer"
      role: "System optimization"
      capabilities: ["performance_analysis", "bottleneck_identification"]
      priority: "high"

  universal_development:
    - name: "@api-architect"
      role: "API design"
      capabilities: ["restful_design", "microservice_coordination"]
      priority: "high"

    - name: "@backend-developer"
      role: "Implementation"
      capabilities: ["async_patterns", "database_operations"]
      priority: "critical"

  specialized_agents:
    frontend:
      - name: "@frontend-developer"
        capabilities: ["dashboard_ui", "websocket_integration"]
        priority: "high"

    framework_specialists:
      django:
        - "@django-api-developer"
        - "@django-backend-expert"
        - "@django-orm-expert"
      laravel:
        - "@laravel-backend-expert"
        - "@laravel-eloquent-expert"
      rails:
        - "@rails-backend-expert"
        - "@rails-api-developer"
        - "@rails-activerecord-expert"
      react:
        - "@react-component-architect"
        - "@react-nextjs-expert"
        - "@react-state-manager"
      vue:
        - "@vue-component-architect"
        - "@vue-nuxt-expert"
        - "@vue-state-manager"

# Project Phases Configuration
phases:
  phase_1:
    name: "Foundation"
    status: "completed"
    completion_date: "2025-07-29"
    milestones:
      - "Core system architecture design"
      - "FastAPI application structure"
      - "Database models and migrations"
      - "Basic MCP server integration"
      - "Agent reliability tracking models"

  phase_2:
    name: "Core Components"
    status: "in_progress"
    completion_percentage: 75
    target_completion: "2025-08-06"
    milestones:
      - name: "CompletionVerifier implementation"
        status: "completed"
        completion_date: "2025-07-30"

      - name: "ProofOfWorkCollector system"
        status: "completed"
        completion_date: "2025-07-30"

      - name: "MCP client integration"
        status: "completed"
        completion_date: "2025-07-31"

      - name: "ToolCallValidator framework"
        status: "completed"
        completion_date: "2025-07-31"

      - name: "TaskRollbackManager enhancement"
        status: "pending"
        priority: "critical"
        target_date: "2025-08-03"
        assigned_agent: "@backend-developer"

      - name: "AgentBehaviorMonitor expansion"
        status: "pending"
        priority: "critical"
        target_date: "2025-08-04"
        assigned_agent: "@performance-optimizer"

      - name: "Real-time dashboard router"
        status: "completed"
        completion_date: "2025-08-01"

  phase_3:
    name: "Documentation Agent System"
    status: "in_progress"
    completion_percentage: 65
    target_completion: "2025-08-12"
    milestones:
      - name: "Project tracking database models"
        status: "completed"
        completion_date: "2025-08-02"

      - name: "Project documentation agent sub-agent"
        status: "completed"
        completion_date: "2025-08-02"

      - name: "Master document templates"
        status: "completed"
        completion_date: "2025-08-02"

      - name: "Auto-update system implementation"
        status: "completed"
        completion_date: "2025-08-02"

      - name: "FastAPI endpoints for project tracking"
        status: "completed"
        completion_date: "2025-08-02"

      - name: "Project plan directory structure"
        status: "in_progress"
        completion_percentage: 75
        target_date: "2025-08-02"
        assigned_agent: "@project-documentation-agent"

      - name: "Git hook integration"
        status: "pending"
        target_date: "2025-08-09"
        assigned_agent: "@code-archaeologist"
        dependencies: ["Project plan directory structure"]

      - name: "Real-time project status dashboard"
        status: "pending"
        target_date: "2025-08-10"
        assigned_agent: "@frontend-developer"
        dependencies: ["FastAPI endpoints", "Dashboard templates"]

  phase_4:
    name: "Integration & Testing"
    status: "planned"
    target_start: "2025-08-13"
    target_completion: "2025-08-27"

  phase_5:
    name: "Production Readiness"
    status: "planned"
    target_start: "2025-08-28"
    target_completion: "2025-09-15"

# Technical Configuration
technical:
  # Database configuration
  database:
    development:
      type: "sqlite"
      url: "sqlite:///./ares_dev.db"

    production:
      type: "postgresql"
      host: "${DATABASE_HOST}"
      port: 5432
      database: "ares_prod"

  # API configuration
  api:
    version: "v1"
    base_url: "/api"
    documentation:
      swagger_ui: true
      redoc: true

  # WebSocket configuration
  websocket:
    connection_timeout: 300
    max_connections: 1000
    heartbeat_interval: 30

  # MCP Servers
  mcp_servers:
    - name: "sqlite"
      capabilities: ["database_operations", "query_execution"]
      priority: "critical"

    - name: "postgresql"
      capabilities: ["production_database", "advanced_queries"]
      priority: "high"

    - name: "eslint-quality"
      capabilities: ["frontend_code_quality", "linting"]
      priority: "medium"

    - name: "code_checker"
      capabilities: ["python_quality", "security_scanning"]
      priority: "high"

    - name: "playwright-enhanced"
      capabilities: ["browser_automation", "e2e_testing"]
      priority: "medium"

    - name: "docker"
      capabilities: ["containerization", "deployment"]
      priority: "high"

    - name: "github-actions"
      capabilities: ["ci_cd", "automation"]
      priority: "high"

    - name: "ripgrep-search"
      capabilities: ["codebase_search", "pattern_matching"]
      priority: "medium"

# Quality Standards
quality:
  code_coverage:
    minimum: 90
    target: 95

  response_time:
    api_endpoints: 200  # milliseconds
    websocket_latency: 50  # milliseconds

  reliability:
    agent_success_rate: 90  # percentage
    system_uptime: 99.9  # percentage

  security:
    vulnerability_tolerance: 0
    security_scan_frequency: "daily"

  documentation:
    completeness: 95  # percentage
    accuracy: 98  # percentage
    freshness: 24  # hours maximum age

# Monitoring and Alerting
monitoring:
  health_checks:
    interval: 60  # seconds
    endpoints:
      - "/health"
      - "/api/project/documentation/status"

  performance_metrics:
    collection_interval: 300  # seconds
    retention_days: 30

  alerting:
    critical_response_time: 120  # seconds
    error_threshold: 5  # percentage
    agent_failure_threshold: 10  # percentage

# Integration Settings
integrations:
  git_hooks:
    enabled: true
    events: ["pre-commit", "post-commit", "pre-push"]
    documentation_update: true

  ci_cd:
    platform: "github_actions"
    automated_testing: true
    automated_deployment: false  # Manual approval required

  external_tools:
    bandit_security_scan: true
    sonarqube_analysis: false  # Planned
    performance_monitoring: true

# Environment Configuration
environments:
  development:
    debug: true
    hot_reload: true
    cors_enabled: true

  staging:
    debug: false
    hot_reload: false
    cors_enabled: true

  production:
    debug: false
    hot_reload: false
    cors_enabled: false
    security_headers: true
    rate_limiting: true

# Backup and Recovery
backup:
  database:
    frequency: "daily"
    retention_days: 30

  documentation:
    frequency: "hourly"
    retention_days: 7

  configuration:
    frequency: "weekly"
    retention_days: 90
